### ISSUE TITLE
data not binding in view

### ISSUE THREAD

**Issue by geegirls3** [wstaeblein/ngSimpleDatePick#1]
Im using this Date Picker in my project. It works when I test it in a static environment, but when I add it to my project the data does not bind. It pops up but I only see the code not values. I followed your instructions but can't figure out why it is not working in my project. 

http://stackoverflow.com/q/31360573/1636957

**Comment by wstaeblein** [comment]
Hi there,

Can you post your controller and main angular module?

**Comment by wstaeblein** [comment]
One more thing, You have included Angular and JQuery in your project, right?
